// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoAddMaterial(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GoAddMaterial'](arg1, arg2, arg3, arg4);
}

export function GoSearchMaterials(arg1, arg2, arg3) {
  return window['go']['main']['App']['GoSearchMaterials'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
