// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoAddComponent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GoAddComponent'](arg1, arg2, arg3, arg4);
}

export function GoAddMaterial(arg1, arg2) {
  return window['go']['main']['App']['GoAddMaterial'](arg1, arg2);
}

export function GoGetAllMaterial() {
  return window['go']['main']['App']['GoGetAllMaterial']();
}

export function GoSearchComponents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GoSearchComponents'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
