// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GoAddMaterial(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GoSearchMaterials(arg1:string,arg2:string,arg3:string):Promise<Array<main.Material>>;

export function Greet(arg1:string):Promise<string>;
